// backend/src/common/geography-hierarchy.ts
export const geographyHierarchy = {
    "Africa": [
      "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Republic",
      "Chad", "Comoros", "Congo (Congo-Brazzaville)", "Democratic Republic of the Congo", "Djibouti", "Egypt", "Equatorial Guinea",
      "Eritrea", "Eswatini (fmr. 'Swaziland')", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast",
      "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique",
      "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "Somalia",
      "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"
    ],
    "Asia": [
      "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "Cyprus",
      "Georgia", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan",
      "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar (Burma)", "Nepal", "North Korea", "Oman", "Pakistan",
      "Palestine", "Philippines", "Qatar", "Russia", "Saudi Arabia", "Singapore", "South Korea", "Sri Lanka", "Syria",
      "Taiwan", "Tajikistan", "Thailand", "Timor-Leste", "Turkey", "Turkmenistan", "United Arab Emirates", "Uzbekistan",
      "Vietnam", "Yemen"
    ],
    "Europe": [
      "Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Czechia",
      "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo",
      "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands",
      "North Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia",
      "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom", "Vatican City"
    ],
    "North America": [
      "Antigua and Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa Rica", "Cuba", "Dominica", "Dominican Republic",
      "El Salvador", "Grenada", "Guatemala", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Saint Kitts and Nevis",
      "Saint Lucia", "Saint Vincent and the Grenadines", "Trinidad and Tobago", "United States"
    ],
    "Oceania": [
      "Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", "Palau", "Papua New Guinea",
      "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu"
    ],
    "South America": [
      "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"
    ],
    // Individual country mapping for direct lookup (204 countries)
    "Afghanistan": ["Afghanistan"],
    "Albania": ["Albania"],
    "Algeria": ["Algeria"],
    "Andorra": ["Andorra"],
    "Angola": ["Angola"],
    "Antigua and Barbuda": ["Antigua and Barbuda"],
    "Argentina": ["Argentina"],
    "Armenia": ["Armenia"],
    "Australia": ["Australia"],
    "Austria": ["Austria"],
    "Azerbaijan": ["Azerbaijan"],
    "Bahamas": ["Bahamas"],
    "Bahrain": ["Bahrain"],
    "Bangladesh": ["Bangladesh"],
    "Barbados": ["Barbados"],
    "Belarus": ["Belarus"],
    "Belgium": ["Belgium"],
    "Belize": ["Belize"],
    "Benin": ["Benin"],
    "Bhutan": ["Bhutan"],
    "Bolivia": ["Bolivia"],
    "Bosnia and Herzegovina": ["Bosnia and Herzegovina"],
    "Botswana": ["Botswana"],
    "Brazil": ["Brazil"],
    "Brunei": ["Brunei"],
    "Bulgaria": ["Bulgaria"],
    "Burkina Faso": ["Burkina Faso"],
    "Burundi": ["Burundi"],
    "Cabo Verde": ["Cabo Verde"],
    "Cambodia": ["Cambodia"],
    "Cameroon": ["Cameroon"],
    "Canada": ["Canada"],
    "Central African Republic": ["Central African Republic"],
    "Chad": ["Chad"],
    "Chile": ["Chile"],
    "China": ["China"],
    "Colombia": ["Colombia"],
    "Comoros": ["Comoros"],
    "Congo (Congo-Brazzaville)": ["Congo (Congo-Brazzaville)"],
    "Democratic Republic of the Congo": ["Democratic Republic of the Congo"],
    "Costa Rica": ["Costa Rica"],
    "Croatia": ["Croatia"],
    "Cuba": ["Cuba"],
    "Cyprus": ["Cyprus"],
    "Czechia": ["Czechia"],
    "Denmark": ["Denmark"],
    "Djibouti": ["Djibouti"],
    "Dominica": ["Dominica"],
    "Dominican Republic": ["Dominican Republic"],
    "Ecuador": ["Ecuador"],
    "Egypt": ["Egypt"],
    "El Salvador": ["El Salvador"],
    "Equatorial Guinea": ["Equatorial Guinea"],
    "Eritrea": ["Eritrea"],
    "Estonia": ["Estonia"],
    "Eswatini (fmr. 'Swaziland')": ["Eswatini (fmr. 'Swaziland')"],
    "Ethiopia": ["Ethiopia"],
    "Fiji": ["Fiji"],
    "Finland": ["Finland"],
    "France": ["France"],
    "Gabon": ["Gabon"],
    "Gambia": ["Gambia"],
    "Georgia": ["Georgia"],
    "Germany": ["Germany"],
    "Ghana": ["Ghana"],
    "Greece": ["Greece"],
    "Grenada": ["Grenada"],
    "Guatemala": ["Guatemala"],
    "Guinea": ["Guinea"],
    "Guinea-Bissau": ["Guinea-Bissau"],
    "Guyana": ["Guyana"],
    "Haiti": ["Haiti"],
    "Honduras": ["Honduras"],
    "Hungary": ["Hungary"],
    "Iceland": ["Iceland"],
    "India": ["India"],
    "Indonesia": ["Indonesia"],
    "Iran": ["Iran"],
    "Iraq": ["Iraq"],
    "Ireland": ["Ireland"],
    "Israel": ["Israel"],
    "Italy": ["Italy"],
    "Ivory Coast": ["Ivory Coast"],
    "Jamaica": ["Jamaica"],
    "Japan": ["Japan"],
    "Jordan": ["Jordan"],
    "Kazakhstan": ["Kazakhstan"],
    "Kenya": ["Kenya"],
    "Kiribati": ["Kiribati"],
    "Kosovo": ["Kosovo"],
    "Kuwait": ["Kuwait"],
    "Kyrgyzstan": ["Kyrgyzstan"],
    "Laos": ["Laos"],
    "Latvia": ["Latvia"],
    "Lebanon": ["Lebanon"],
    "Lesotho": ["Lesotho"],
    "Liberia": ["Liberia"],
    "Libya": ["Libya"],
    "Liechtenstein": ["Liechtenstein"],
    "Lithuania": ["Lithuania"],
    "Luxembourg": ["Luxembourg"],
    "Madagascar": ["Madagascar"],
    "Malawi": ["Malawi"],
    "Malaysia": ["Malaysia"],
    "Maldives": ["Maldives"],
    "Mali": ["Mali"],
    "Malta": ["Malta"],
    "Marshall Islands": ["Marshall Islands"],
    "Mauritania": ["Mauritania"],
    "Mauritius": ["Mauritius"],
    "Mexico": ["Mexico"],
    "Micronesia": ["Micronesia"],
    "Moldova": ["Moldova"],
    "Monaco": ["Monaco"],
    "Mongolia": ["Mongolia"],
    "Montenegro": ["Montenegro"],
    "Morocco": ["Morocco"],
    "Mozambique": ["Mozambique"],
    "Myanmar (Burma)": ["Myanmar (Burma)"],
    "Namibia": ["Namibia"],
    "Nauru": ["Nauru"],
    "Nepal": ["Nepal"],
    "Netherlands": ["Netherlands"],
    "New Zealand": ["New Zealand"],
    "Nicaragua": ["Nicaragua"],
    "Niger": ["Niger"],
    "Nigeria": ["Nigeria"],
    "North Korea": ["North Korea"],
    "North Macedonia": ["North Macedonia"],
    "Norway": ["Norway"],
    "Oman": ["Oman"],
    "Pakistan": ["Pakistan"],
    "Palau": ["Palau"],
    "Palestine": ["Palestine"],
    "Panama": ["Panama"],
    "Papua New Guinea": ["Papua New Guinea"],
    "Paraguay": ["Paraguay"],
    "Peru": ["Peru"],
    "Philippines": ["Philippines"],
    "Poland": ["Poland"],
    "Portugal": ["Portugal"],
    "Qatar": ["Qatar"],
    "Romania": ["Romania"],
    "Russia": ["Russia"],
    "Rwanda": ["Rwanda"],
    "Saint Kitts and Nevis": ["Saint Kitts and Nevis"],
    "Saint Lucia": ["Saint Lucia"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines"],
    "Samoa": ["Samoa"],
    "San Marino": ["San Marino"],
    "Sao Tome and Principe": ["Sao Tome and Principe"],
    "Saudi Arabia": ["Saudi Arabia"],
    "Senegal": ["Senegal"],
    "Serbia": ["Serbia"],
    "Seychelles": ["Seychelles"],
    "Sierra Leone": ["Sierra Leone"],
    "Singapore": ["Singapore"],
    "Slovakia": ["Slovakia"],
    "Slovenia": ["Slovenia"],
    "Solomon Islands": ["Solomon Islands"],
    "Somalia": ["Somalia"],
    "South Africa": ["South Africa"],
    "South Korea": ["South Korea"],
    "South Sudan": ["South Sudan"],
    "Spain": ["Spain"],
    "Sri Lanka": ["Sri Lanka"],
    "Sudan": ["Sudan"],
    "Suriname": ["Suriname"],
    "Sweden": ["Sweden"],
    "Switzerland": ["Switzerland"],
    "Syria": ["Syria"],
    "Taiwan": ["Taiwan"],
    "Tajikistan": ["Tajikistan"],
    "Tanzania": ["Tanzania"],
    "Thailand": ["Thailand"],
    "Timor-Leste": ["Timor-Leste"],
    "Togo": ["Togo"],
    "Tonga": ["Tonga"],
    "Trinidad and Tobago": ["Trinidad and Tobago"],
    "Tunisia": ["Tunisia"],
    "Turkey": ["Turkey"],
    "Turkmenistan": ["Turkmenistan"],
    "Tuvalu": ["Tuvalu"],
    "Uganda": ["Uganda"],
    "Ukraine": ["Ukraine"],
    "United Arab Emirates": ["United Arab Emirates"],
    "United Kingdom": ["United Kingdom"],
    "United States": ["United States"],
    "Uruguay": ["Uruguay"],
    "Uzbekistan": ["Uzbekistan"],
    "Vanuatu": ["Vanuatu"],
    "Vatican City": ["Vatican City"],
    "Venezuela": ["Venezuela"],
    "Vietnam": ["Vietnam"],
    "Yemen": ["Yemen"],
    "Zambia": ["Zambia"],
    "Zimbabwe": ["Zimbabwe"]
  };
  
  export function expandCountryOrRegion(selected: string): string[] {
    // If it's a top-level region (continent), return all subregions
    if (geographyHierarchy[selected]) {
      return geographyHierarchy[selected];
    }
    // Otherwise, return itself
    return [selected];
  }
  
